"""Badminton coach domain helpers."""

from .clarification_policy import build_clarification_request
from .health_image import (
    HealthImageObservation,
    HealthRecoveryAdvice,
    analyze_health_image_text,
    build_health_recovery_advice,
)
from .intent import (
    CoachIntent,
    CoachIntentClassifier,
    CoachIntentName,
    CoachRiskLevel,
    classify_coach_intent,
    detect_coach_intent,
    normalize_intent_payload,
)
from .memory_profile import CoachMemoryResult, handle_check_memory
from .persona import (
    CoachEncouragementStyle,
    CoachPersonaConfig,
    CoachPersonaOverride,
    CoachQuestioningStyle,
    CoachStrictness,
    CoachTone,
    CoachVerbosity,
    build_agent_coach_persona,
    default_coach_persona,
    merge_coach_persona,
    resolve_coach_persona,
    resolve_coach_persona_overrides,
    resolve_coach_personality_id,
    resolve_runtime_coach_persona,
)
from .postmatch import Improvement, PostmatchReview, TechnicalObservation, extract_postmatch_review
from .prematch import PrematchAdvice, build_prematch_advice, load_recent_review_logs
from .profile_store import (
    HealthPersistenceResult,
    PostmatchPersistenceResult,
    PrematchPersistenceResult,
    append_body_metric,
    append_review_log,
    append_training_log,
    create_default_coach_profile,
    extract_body_facts,
    extract_training_facts,
    load_coach_profile,
    persist_health_observation,
    persist_postmatch_review,
    persist_prematch_signal,
    process_postmatch_message,
    save_coach_profile,
    update_profile_from_postmatch,
)
from .recall import build_recall_context
from .response_renderer import render_coach_route_payload, resolve_persona_config
from .router import (
    CoachComposableRouteResult,
    CoachSafetyGateDecision,
    CoachSafetyGateHook,
    CoachSingleIntentRouteResult,
    default_coach_safety_gate,
    route_composable_intent,
    route_single_intent,
)
from .training_data import BodyMetricsContext, TrainingLogContext, get_body_metrics_trend, get_recent_training_log
from .upload_cache import cleanup_multimodal_upload_cache, write_multimodal_upload_manifest
from .weather import WeatherContext, degrade_weather_context, fetch_weather_context, normalize_weather_payload

__all__ = [
    "HealthImageObservation",
    "HealthRecoveryAdvice",
    "build_clarification_request",
    "HealthPersistenceResult",
    "CoachMemoryResult",
    "PrematchPersistenceResult",
    "Improvement",
    "CoachIntent",
    "CoachIntentClassifier",
    "CoachIntentName",
    "CoachRiskLevel",
    "CoachPersonaConfig",
    "CoachPersonaOverride",
    "CoachTone",
    "CoachStrictness",
    "CoachVerbosity",
    "CoachQuestioningStyle",
    "CoachEncouragementStyle",
    "CoachComposableRouteResult",
    "CoachSafetyGateDecision",
    "CoachSafetyGateHook",
    "CoachSingleIntentRouteResult",
    "PrematchAdvice",
    "PostmatchPersistenceResult",
    "PostmatchReview",
    "TechnicalObservation",
    "TrainingLogContext",
    "BodyMetricsContext",
    "WeatherContext",
    "analyze_health_image_text",
    "append_body_metric",
    "append_review_log",
    "append_training_log",
    "extract_body_facts",
    "extract_training_facts",
    "build_health_recovery_advice",
    "handle_check_memory",
    "build_prematch_advice",
    "classify_coach_intent",
    "create_default_coach_profile",
    "build_agent_coach_persona",
    "default_coach_persona",
    "detect_coach_intent",
    "degrade_weather_context",
    "extract_postmatch_review",
    "fetch_weather_context",
    "get_body_metrics_trend",
    "get_recent_training_log",
    "load_coach_profile",
    "persist_health_observation",
    "persist_prematch_signal",
    "load_recent_review_logs",
    "normalize_weather_payload",
    "normalize_intent_payload",
    "merge_coach_persona",
    "resolve_coach_persona",
    "resolve_coach_personality_id",
    "resolve_coach_persona_overrides",
    "resolve_runtime_coach_persona",
    "resolve_persona_config",
    "render_coach_route_payload",
    "build_recall_context",
    "persist_postmatch_review",
    "process_postmatch_message",
    "default_coach_safety_gate",
    "route_composable_intent",
    "route_single_intent",
    "save_coach_profile",
    "cleanup_multimodal_upload_cache",
    "write_multimodal_upload_manifest",
    "update_profile_from_postmatch",
]
